# Generated by Django 3.1.7 on 2021-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='event time'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time_convention',
            field=models.CharField(blank=True, choices=[('am', 'am'), ('pm', 'pm')], max_length=2, null=True, verbose_name='time convention'),
        ),
    ]
