# Generated by Django 3.1.7 on 2021-05-25 18:45

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210515_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=20000, verbose_name='description')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.FileField(blank=True, upload_to=events.models.news_directory_path)),
            ],
        ),
    ]
