# Generated by Django 3.1.7 on 2021-07-10 19:13

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=events.models.news_thumbnail_directory_path),
        ),
    ]
