# Generated by Django 3.1.7 on 2021-07-10 19:18

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=events.models.events_thumbnail_directory_path),
        ),
    ]
