# Generated by Django 3.1.7 on 2021-07-13 11:42

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=events.models.news_directory_path),
        ),
    ]
