# Generated by Django 3.1.7 on 2022-01-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_society_registration_number'),
        ('events', '0006_auto_20210713_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
        migrations.AddField(
            model_name='news',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
    ]
