# Generated by Django 3.1.7 on 2022-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, unique=True, verbose_name='mobile number')),
                ('society_name', models.CharField(max_length=100, verbose_name='full name')),
                ('address', models.TextField(max_length=500, verbose_name='address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('pincode', models.CharField(max_length=50, verbose_name='pincode')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('date_of_join', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is active')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
        ),
    ]
