# Generated by Django 3.1.7 on 2022-01-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_society_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='registration_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='registration number'),
        ),
    ]
