# Generated by Django 3.1.7 on 2021-08-22 17:40

from django.db import migrations, models
import security.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('father_name', models.CharField(max_length=100, verbose_name='father name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, verbose_name='gender')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('date_of_joining', models.DateField()),
                ('permanent_address', models.TextField(max_length=500, verbose_name='permanent address')),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=20, verbose_name='mobile number')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='reference')),
                ('photo', models.FileField(upload_to=security.models.security_directory_path)),
                ('photo_thumbnail', models.FileField(upload_to=security.models.security_thumbnail_directory_path)),
                ('adhar_card', models.FileField(upload_to=security.models.security_directory_path)),
                ('adhar_card_thumbnail', models.FileField(upload_to=security.models.security_thumbnail_directory_path)),
            ],
        ),
    ]
