# Generated by Django 3.1.7 on 2021-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=10, verbose_name='status'),
        ),
    ]
