# Generated by Django 3.1.7 on 2021-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_security_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=10, verbose_name='status'),
        ),
    ]
