# Generated by Django 3.1.7 on 2021-08-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20210825_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_timetable', to='security.security')),
            ],
        ),
    ]
