# Generated by Django 3.1.7 on 2022-01-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_auto_20220125_0854'),
        ('security', '0007_auto_20210916_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
    ]
