# Generated by Django 3.1.7 on 2021-12-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_against',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.CharField(blank=True, max_length=100, verbose_name='payment month'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_year',
            field=models.CharField(blank=True, max_length=100, verbose_name='payment year'),
        ),
    ]
