# Generated by Django 3.1.7 on 2021-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20211213_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=15, verbose_name='payment status'),
        ),
    ]
