# Generated by Django 3.1.7 on 2022-01-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_auto_20220125_0854'),
        ('fees', '0004_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesitem',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
    ]
