# Generated by Django 3.1.7 on 2021-04-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210402_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approved',
            new_name='post_status',
        ),
    ]
