# Generated by Django 3.1.7 on 2021-04-02 11:21

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210402_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, upload_to=posts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='title'),
        ),
    ]
