# Generated by Django 3.1.7 on 2021-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_complaintsandgrievances'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsandgrievances',
            name='solution_status',
            field=models.CharField(choices=[('unsolved', 'unsolved'), ('solved', 'solved')], default='unsolved', max_length=15, verbose_name='complaints solution status'),
        ),
    ]
