# Generated by Django 3.1.7 on 2021-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='show_address',
            field=models.BooleanField(blank=True, default=False, verbose_name='show address'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='show_email',
            field=models.BooleanField(blank=True, default=False, verbose_name='show email-id'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='show_number',
            field=models.BooleanField(blank=True, default=False, verbose_name='show contact number'),
        ),
    ]
