# Generated by Django 3.1.7 on 2021-12-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0002_auto_20210506_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='SettingDetails',
        ),
    ]
