# Generated by Django 3.1.7 on 2021-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0003_auto_20211207_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingdetails',
            name='enable_events',
            field=models.BooleanField(blank=True, default=True, verbose_name='enable events'),
        ),
        migrations.AddField(
            model_name='settingdetails',
            name='enable_news',
            field=models.BooleanField(blank=True, default=True, verbose_name='enable news'),
        ),
        migrations.AddField(
            model_name='settingdetails',
            name='enable_posts',
            field=models.BooleanField(blank=True, default=True, verbose_name='enable posts'),
        ),
        migrations.AddField(
            model_name='settingdetails',
            name='show_complaints',
            field=models.BooleanField(blank=True, default=True, verbose_name='show complaints'),
        ),
        migrations.AlterField(
            model_name='settingdetails',
            name='show_address',
            field=models.BooleanField(blank=True, default=True, verbose_name='show address'),
        ),
        migrations.AlterField(
            model_name='settingdetails',
            name='show_email',
            field=models.BooleanField(blank=True, default=True, verbose_name='show email-id'),
        ),
        migrations.AlterField(
            model_name='settingdetails',
            name='show_number',
            field=models.BooleanField(blank=True, default=True, verbose_name='show contact number'),
        ),
    ]
