# Generated by Django 3.1.7 on 2022-01-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_auto_20220125_0854'),
        ('config_ui', '0004_auto_20211207_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingdetails',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
    ]
