# Generated by Django 3.1.7 on 2021-02-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=15, verbose_name='user role'),
        ),
    ]
