# Generated by Django 3.1.7 on 2021-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4, verbose_name='otp')),
                ('user', models.CharField(max_length=20, verbose_name='user')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='active')),
            ],
        ),
    ]
