# Generated by Django 3.1.7 on 2021-06-21 19:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='data',
            field=models.JSONField(default=users.models.my_default_json),
        ),
        migrations.AddField(
            model_name='otp',
            name='matched',
            field=models.BooleanField(blank=True, default=False, verbose_name='matched'),
        ),
    ]
