# Generated by Django 3.1.7 on 2021-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_otp_otp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('password', 'password'), ('forgot_password', 'forgot_password'), ('number_change', 'number_change'), ('signup', 'signup')], max_length=50, verbose_name='otp type'),
        ),
    ]
