# Generated by Django 3.1.7 on 2021-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210629_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='relation',
            field=models.CharField(choices=[('husband', 'husband'), ('wife', 'wife'), ('father', 'father'), ('mother', 'mother'), ('son', 'son'), ('daughter', 'daughter'), ('brother', 'brother'), ('sister', 'sister'), ('other', 'other')], default='other', max_length=50, verbose_name='type of relation'),
        ),
    ]
