# Generated by Django 3.1.7 on 2022-01-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20220120_1111'),
        ('users', '0009_auto_20210716_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='is admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super', 'super'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=15, verbose_name='user role'),
        ),
    ]
